# Docker compose for udacity project.
# Spark images from Big Data Europe
# https://github.com/big-data-europe/docker-spark
version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.2
    ports:
    - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
    networks:
      - crosa-labs-network

  kafka:
    image: confluentinc/cp-kafka:5.2.2
    ports:
    - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    depends_on:
    - "zookeeper"
    networks:
      - crosa-labs-network
  # kafdrop is a really nice tool to visually see how your kafka cluster.
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"
    networks:
      - crosa-labs-network
  spark-master:
    image: bde2020/spark-master:2.4.3-hadoop2.7
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    environment:
      - "INIT_DAEMON_STEP=setup_spark"
    volumes:
      - ./spark:/tmp/sfcrime/
    networks:
      - crosa-labs-network

  spark-worker-1:
    image: bde2020/spark-worker:2.4.3-hadoop2.7
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "INIT_DAEMON_STEP=setup_spark"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=4"
      - "SPARK_WORKER_MEMORY=1g"
    networks:
      - crosa-labs-network

  spark-worker-2:
    image: bde2020/spark-worker:2.4.3-hadoop2.7
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "INIT_DAEMON_STEP=setup_spark"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=4"
      - "SPARK_WORKER_MEMORY=1g"
    networks:
      - crosa-labs-network

networks:
  crosa-labs-network:
    driver: bridge
    name: crosa-labs-network